name: Build and Deploy to Azure Web Apps

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_PREFIX: teamhitori/quick-cache-web  # Replace with your Docker Hub username and app prefix

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Get commit count
        id: git-count
        run: echo "::set-output name=commit-count::$(git rev-list --count HEAD)"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Prepare Docker Compose File
        run: |
          $env:VERSION_TAG = Get-Date -Format "yyMMdd-HHmm"
          Get-Content .\docker-compose-remote-template.yml | ForEach-Object { $_.Replace("<version>", $env:VERSION_TAG) } | Out-File -FilePath .\docker-compose-remote.yml -Encoding UTF8
        shell: pwsh

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose-remote.yml  build
          docker-compose -f docker-compose-remote.yml  push
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web Apps
        run: |
          ls
          az webapp create -g teamhitori-quick-cache-prod --plan teamhitori-quick-cache-prod-plan -n teamhitori-quick-cache-prod-webapp --multicontainer-config-type compose --multicontainer-config-file docker-compose-remote.yml

      - name: Logout from Azure
        run: az logout
